#!/usr/bin/env bash
# PreToolUse hook for Edit|Write — blocks edits to sensitive paths.
#
# Reads the hook payload from stdin (JSON with .tool_input.file_path) and
# exits with code 2 (block + feedback to Claude) if the file matches the
# blocklist below. Exits 0 otherwise.
#
# Blocklist:
#   - Any .env / .env.* file (secrets land here).
#   - deno.lock at any depth (Deno-managed; never edit by hand).
#   - Anything inside a .git/ directory.
#
# To extend the blocklist, add a new case branch and document why.
set -euo pipefail

INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ -z "$FILE" ]]; then
  exit 0
fi

case "$FILE" in
  *.env|*.env.local|*.env.*.local|*.env.production|*.env.development|*.env.staging|*.env.test)
    echo "BLOCKED by protect-sensitive-files: edits to env files ('$FILE') are not allowed via this hook. If you genuinely need to update a non-secret env example, do it manually outside Claude Code or remove this guard for the session." >&2
    exit 2
    ;;
  */deno.lock|deno.lock)
    echo "BLOCKED by protect-sensitive-files: deno.lock is generated by the Deno runtime — never edit by hand. If a dependency change requires it, run 'deno cache' or the appropriate 'deno task' command." >&2
    exit 2
    ;;
  */.git/*|*/.git|.git/*)
    echo "BLOCKED by protect-sensitive-files: writes inside .git/ are not allowed via this hook (use plain git commands)." >&2
    exit 2
    ;;
esac

exit 0
