/**
 * @fileoverview The `docs:generate` command: scan the app's controllers and
 * write an OpenAPI document from their route metadata.
 *
 * @module @lockness/openapi/cli_commands
 */

import type { Cli } from '@lockness/cli'
// The subpath, never the barrel: `mod.ts` re-exports this module, so a barrel
// import would load every built-in command into `@lockness/openapi` (#436).
import { CommandFailedError } from '@lockness/cli/command-failure'
import { generateOpenAPISpec } from './generator.ts'
import { loadDocumentedControllers } from './discovery.ts'
import type { ControllerClass } from '@lockness/contract'

/**
 * Register the OpenAPI commands.
 *
 * Commands registered:
 * - docs:generate - Write an OpenAPI document from the app's controllers. It
 *   fails by throwing, so `Cli.dispatch` prints the failure once and returns a
 *   non-zero status.
 *
 * @param cli - The CLI instance to register commands on.
 *
 * @example
 * ```ts
 * registerOpenAPICommands(cli)
 * ```
 */
export function registerOpenAPICommands(cli: Cli): void {
    cli.register(
        'docs:generate',
        async (args: string[]) => {
            console.log('📝 Generating OpenAPI specification...\n')

            // Parse options
            const options = parseOptions(args)

            // Get all controllers
            let controllers: ControllerClass[]
            try {
                controllers = await loadDocumentedControllers()
            } catch (error) {
                // D4 rule 2: name the step, carry the error as the cause;
                // `Cli.dispatch` prints both once and exits non-zero (#436).
                throw new CommandFailedError('Could not scan the controllers', {
                    cause: error,
                })
            }

            // Generate spec
            const spec = generateOpenAPISpec(controllers, {
                title: options.title || 'Lockness API',
                version: options.version || '1.0.0',
                description:
                    'API documentation generated by Lockness OpenAPI generator',
            })

            // Write to file
            const outputPath = options.output || 'public/openapi.json'
            await Deno.writeTextFile(
                outputPath,
                JSON.stringify(spec, null, 2),
            )

            console.log(`✅ OpenAPI spec generated at: ${outputPath}`)
            console.log(
                `   Found ${
                    Object.keys(spec.paths).length
                } documented endpoints`,
            )
            console.log(`   ${spec.tags?.length || 0} tags`)
            console.log(`\n💡 View docs at: http://localhost:8888/api-docs`)
        },
        'Generate OpenAPI specification from controllers',
    )
}

function parseOptions(args: string[]): {
    output?: string
    title?: string
    version?: string
} {
    const options: { output?: string; title?: string; version?: string } = {}

    for (let i = 0; i < args.length; i++) {
        const arg = args[i]
        if (arg === '--output' || arg === '-o') {
            options.output = args[++i]
        } else if (arg === '--title' || arg === '-t') {
            options.title = args[++i]
        } else if (arg === '--version' || arg === '-v') {
            options.version = args[++i]
        }
    }

    return options
}
