/**
 * @fileoverview The `docs:generate` command: scan the app's controllers and
 * write an OpenAPI document from their route metadata.
 *
 * @module @lockness/openapi/cli_commands
 */

import type { Cli } from '@lockness/cli'
import { generateOpenAPISpec } from './generator.ts'
import {
    type ControllerClass,
    importAppFile,
    renderError,
    safeForLog,
} from '@lockness/contract'
import { join } from '@std/path'

/**
 * Import every `*_controller.ts(x)` file of a directory and collect the
 * exports whose name ends in `Controller`, for `docs:generate`.
 *
 * Any failure stops the scan: a document missing a controller would look
 * complete. A file that fails to load is named in the error.
 *
 * @param dir - The directory, absolute or relative to the working directory.
 * @returns The controller classes, in directory order.
 * @throws When the directory cannot be read, or a controller file fails to
 *   load.
 * @internal Exported for tests.
 *
 * @example
 * ```ts
 * const controllers = await loadDocumentedControllers()
 * ```
 */
export async function loadDocumentedControllers(
    dir: string = join('app', 'controller'),
): Promise<ControllerClass[]> {
    const controllers: ControllerClass[] = []
    for await (const entry of Deno.readDir(dir)) {
        if (
            !entry.isFile ||
            !(entry.name.endsWith('_controller.ts') ||
                entry.name.endsWith('_controller.tsx'))
        ) continue

        let module: Record<string, unknown>
        try {
            // Through the app root, never a `file://` template literal:
            // `deno publish` rewrites one into a path that resolves against
            // the registry (#477).
            module = await importAppFile(join(dir, entry.name))
        } catch (error) {
            throw new Error(
                `${safeForLog(entry.name)} failed to load: ${
                    renderError(error)
                }`,
                { cause: error },
            )
        }

        for (const [key, exported] of Object.entries(module)) {
            if (typeof exported === 'function' && key.endsWith('Controller')) {
                controllers.push(exported as ControllerClass)
            }
        }
    }
    return controllers
}

/**
 * Register the OpenAPI commands.
 *
 * Commands registered:
 * - docs:generate - Write an OpenAPI document from the app's controllers
 *
 * @param cli - The CLI instance to register commands on.
 *
 * @example
 * ```ts
 * registerOpenAPICommands(cli)
 * ```
 */
export function registerOpenAPICommands(cli: Cli): void {
    cli.register(
        'docs:generate',
        async (args: string[]) => {
            console.log('📝 Generating OpenAPI specification...\n')

            // Parse options
            const options = parseOptions(args)

            // Get all controllers
            let controllers: ControllerClass[]
            try {
                controllers = await loadDocumentedControllers()
            } catch (error) {
                console.error(
                    `❌ Error scanning controllers: ${renderError(error)}`,
                )
                return
            }

            // Generate spec
            const spec = generateOpenAPISpec(controllers, {
                title: options.title || 'Lockness API',
                version: options.version || '1.0.0',
                description:
                    'API documentation generated by Lockness OpenAPI generator',
            })

            // Write to file
            const outputPath = options.output || 'public/openapi.json'
            await Deno.writeTextFile(
                outputPath,
                JSON.stringify(spec, null, 2),
            )

            console.log(`✅ OpenAPI spec generated at: ${outputPath}`)
            console.log(
                `   Found ${
                    Object.keys(spec.paths).length
                } documented endpoints`,
            )
            console.log(`   ${spec.tags?.length || 0} tags`)
            console.log(`\n💡 View docs at: http://localhost:8888/api-docs`)
        },
        'Generate OpenAPI specification from controllers',
    )
}

function parseOptions(args: string[]): {
    output?: string
    title?: string
    version?: string
} {
    const options: { output?: string; title?: string; version?: string } = {}

    for (let i = 0; i < args.length; i++) {
        const arg = args[i]
        if (arg === '--output' || arg === '-o') {
            options.output = args[++i]
        } else if (arg === '--title' || arg === '-t') {
            options.title = args[++i]
        } else if (arg === '--version' || arg === '-v') {
            options.version = args[++i]
        }
    }

    return options
}
