/**
 * @fileoverview Tests for the routes generator module.
 *
 * Tests the controller scanning and routes file generation utilities.
 *
 * @module @lockness/core/tests/routes_generator
 */

import { assertEquals, assertStringIncludes } from '@std/assert'
import { existsSync } from '@std/fs'
import {
    type ControllerInfo,
    generateRoutesContent,
    scanControllers,
} from '../routing/generator.ts'

// =============================================================================
// Test Helpers
// =============================================================================

const TEST_DIR = './.test-routes-output'

async function setupTestDir(): Promise<void> {
    await cleanupTestDir()
    await Deno.mkdir(TEST_DIR, { recursive: true })
}

async function cleanupTestDir(): Promise<void> {
    if (existsSync(TEST_DIR)) {
        await Deno.remove(TEST_DIR, { recursive: true })
    }
}

async function setupControllerDir(): Promise<void> {
    await setupTestDir()
    await Deno.mkdir(`${TEST_DIR}/controller`, { recursive: true })
}

// =============================================================================
// generateRoutesContent Tests
// =============================================================================

Deno.test('generateRoutesContent - generates empty registry for no controllers', () => {
    const content = generateRoutesContent([])

    assertStringIncludes(content, 'AUTO-GENERATED FILE')
    assertStringIncludes(content, 'export const controllers = [')
    assertStringIncludes(content, ']')
})

Deno.test('generateRoutesContent - generates imports for controllers', () => {
    const controllers: ControllerInfo[] = [
        {
            className: 'AppController',
            fileName: 'app_controller.tsx',
            importPath: '@controller/app_controller.tsx',
        },
        {
            className: 'UserController',
            fileName: 'user_controller.ts',
            importPath: '@controller/user_controller.ts',
        },
    ]

    const content = generateRoutesContent(controllers)

    assertStringIncludes(
        content,
        "import { AppController } from '@controller/app_controller.tsx'",
    )
    assertStringIncludes(
        content,
        "import { UserController } from '@controller/user_controller.ts'",
    )
    assertStringIncludes(content, 'AppController,')
    assertStringIncludes(content, 'UserController,')
})

Deno.test('generateRoutesContent - includes auto-generated header', () => {
    const content = generateRoutesContent([])

    assertStringIncludes(content, 'Controllers Registry')
    assertStringIncludes(content, 'AUTO-GENERATED FILE - DO NOT EDIT MANUALLY')
    assertStringIncludes(
        content,
        'automatically generated by the routes system',
    )
})

// =============================================================================
// scanControllers Tests
// =============================================================================

Deno.test('scanControllers - returns empty array for empty directory', async () => {
    await setupControllerDir()

    try {
        const controllers = await scanControllers(`${TEST_DIR}/controller`)
        assertEquals(controllers.length, 0)
    } finally {
        await cleanupTestDir()
    }
})

Deno.test('scanControllers - discovers .ts files', async () => {
    await setupControllerDir()

    try {
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/api_controller.ts`,
            'export class ApiController {}',
        )

        const controllers = await scanControllers(`${TEST_DIR}/controller`)

        assertEquals(controllers.length, 1)
        assertEquals(controllers[0].className, 'ApiController')
        assertEquals(controllers[0].fileName, 'api_controller.ts')
        assertEquals(controllers[0].importPath, '@controller/api_controller.ts')
    } finally {
        await cleanupTestDir()
    }
})

Deno.test('scanControllers - discovers .tsx files', async () => {
    await setupControllerDir()

    try {
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/app_controller.tsx`,
            'export class AppController {}',
        )

        const controllers = await scanControllers(`${TEST_DIR}/controller`)

        assertEquals(controllers.length, 1)
        assertEquals(controllers[0].className, 'AppController')
        assertEquals(controllers[0].fileName, 'app_controller.tsx')
    } finally {
        await cleanupTestDir()
    }
})

Deno.test('scanControllers - converts snake_case to PascalCase', async () => {
    await setupControllerDir()

    try {
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/user_auth_controller.ts`,
            'export class UserAuthController {}',
        )

        const controllers = await scanControllers(`${TEST_DIR}/controller`)

        assertEquals(controllers[0].className, 'UserAuthController')
    } finally {
        await cleanupTestDir()
    }
})

Deno.test('scanControllers - sorts controllers by class name', async () => {
    await setupControllerDir()

    try {
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/zebra_controller.ts`,
            'export class ZebraController {}',
        )
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/alpha_controller.ts`,
            'export class AlphaController {}',
        )
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/beta_controller.ts`,
            'export class BetaController {}',
        )

        const controllers = await scanControllers(`${TEST_DIR}/controller`)

        assertEquals(controllers.length, 3)
        assertEquals(controllers[0].className, 'AlphaController')
        assertEquals(controllers[1].className, 'BetaController')
        assertEquals(controllers[2].className, 'ZebraController')
    } finally {
        await cleanupTestDir()
    }
})

Deno.test('scanControllers - ignores non-ts files', async () => {
    await setupControllerDir()

    try {
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/app_controller.ts`,
            'export class AppController {}',
        )
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/readme.md`,
            '# Controllers',
        )
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/config.json`,
            '{}',
        )

        const controllers = await scanControllers(`${TEST_DIR}/controller`)

        assertEquals(controllers.length, 1)
        assertEquals(controllers[0].className, 'AppController')
    } finally {
        await cleanupTestDir()
    }
})

// =============================================================================
// Integration Tests
// =============================================================================

Deno.test('scanControllers + generateRoutesContent - full workflow', async () => {
    await setupControllerDir()

    try {
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/app_controller.tsx`,
            'export class AppController {}',
        )
        await Deno.writeTextFile(
            `${TEST_DIR}/controller/user_controller.ts`,
            'export class UserController {}',
        )

        const controllers = await scanControllers(`${TEST_DIR}/controller`)
        const content = generateRoutesContent(controllers)

        // Write to file
        const outputPath = `${TEST_DIR}/routes.ts`
        await Deno.writeTextFile(outputPath, content)

        assertEquals(existsSync(outputPath), true)

        const written = await Deno.readTextFile(outputPath)
        assertStringIncludes(written, 'AppController')
        assertStringIncludes(written, 'UserController')
        assertStringIncludes(written, 'export const controllers')
    } finally {
        await cleanupTestDir()
    }
})
