/**
 * @fileoverview Routes registry generator for production builds.
 *
 * Utilities for auto-generating routes registry from controller files.
 * In development mode, controllers are auto-discovered. In production,
 * this registry is used for faster startup.
 *
 * @module @lockness/contract/routing/generator
 */

import { walk } from '@std/fs'
import { basename } from '@std/path'

/**
 * Information about a discovered controller.
 */
export interface ControllerInfo {
    /** PascalCase class name (e.g., 'UserController') */
    readonly className: string
    /** Original file name (e.g., 'user_controller.tsx') */
    readonly fileName: string
    /** Import path using @controller alias */
    readonly importPath: string
}

/**
 * Scan a directory for controller files.
 */
export async function scanControllers(
    controllerDir: string,
    extensions: ReadonlyArray<string> = ['tsx', 'ts'],
): Promise<ControllerInfo[]> {
    const controllers: ControllerInfo[] = []

    try {
        for await (
            const entry of walk(controllerDir, { exts: [...extensions] })
        ) {
            if (entry.isFile) {
                const fileName = basename(entry.path)
                const fileNameWithoutExt = fileName.replace(
                    /\.(tsx?|jsx?)$/,
                    '',
                )

                // Convert file name to class name (snake_case to PascalCase)
                const className = fileNameWithoutExt
                    .split('_')
                    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                    .join('')

                const importPath = `@controller/${fileName}`

                controllers.push({
                    className,
                    fileName,
                    importPath,
                })
            }
        }
    } catch (error) {
        throw new Error(
            `Failed to scan controllers: ${(error as Error).message}`,
        )
    }

    // Sort by class name for consistency
    return controllers.sort((a, b) => a.className.localeCompare(b.className))
}

/**
 * Generate the content for the routes registry file.
 */
export function generateRoutesContent(
    controllers: ReadonlyArray<ControllerInfo>,
): string {
    const imports = controllers.map(
        (c) => `import { ${c.className} } from '${c.importPath}'`,
    )

    const classNames = controllers.map((c) => c.className)

    return `/**
 * Controllers Registry
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by the routes system
 * 
 * In development mode (APP_ENV=development), controllers are auto-discovered.
 * In production/compile mode, this registry is used.
 */

${imports.join('\n')}

export const controllers = [
    ${classNames.join(',\n    ')},
]
`
}

/**
 * Result of routes file generation.
 */
export interface GenerateRoutesResult {
    /** Number of controllers found */
    readonly count: number
    /** List of controller class names */
    readonly controllers: ReadonlyArray<string>
}

/**
 * Scan controllers and generate a routes registry file.
 */
export async function generateRoutesFile(
    controllerDir: string,
    outputFile: string,
): Promise<GenerateRoutesResult> {
    const controllers = await scanControllers(controllerDir)
    const content = generateRoutesContent(controllers)

    await Deno.writeTextFile(outputFile, content)

    return {
        count: controllers.length,
        controllers: controllers.map((c) => c.className),
    }
}
