/**
 * Routes Registry Generator
 * 
 * Utilities for auto-generating routes registry from controller files
 */

import { walk } from '@std/fs'
import { basename } from '@std/path'

export interface ControllerInfo {
    className: string
    fileName: string
    importPath: string
}

export async function scanControllers(
    controllerDir: string,
    extensions: string[] = ['tsx', 'ts'],
): Promise<ControllerInfo[]> {
    const controllers: ControllerInfo[] = []

    try {
        for await (const entry of walk(controllerDir, { exts: extensions })) {
            if (entry.isFile) {
                const fileName = basename(entry.path)
                const fileNameWithoutExt = fileName.replace(/\.(tsx?|jsx?)$/, '')

                // Convert file name to class name (snake_case to PascalCase)
                const className = fileNameWithoutExt
                    .split('_')
                    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                    .join('')

                const importPath = `@controller/${fileName}`

                controllers.push({
                    className,
                    fileName,
                    importPath,
                })
            }
        }
    } catch (error) {
        throw new Error(`Failed to scan controllers: ${(error as Error).message}`)
    }

    // Sort by class name for consistency
    return controllers.sort((a, b) => a.className.localeCompare(b.className))
}

export function generateRoutesContent(controllers: ControllerInfo[]): string {
    const imports = controllers.map(
        (c) => `import { ${c.className} } from '${c.importPath}'`,
    )

    const classNames = controllers.map((c) => c.className)

    return `/**
 * Controllers Registry
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by the routes system
 * 
 * In development mode (APP_ENV=development), controllers are auto-discovered.
 * In production/compile mode, this registry is used.
 */

${imports.join('\n')}

export const controllers = [
    ${classNames.join(',\n    ')},
]
`
}

export async function generateRoutesFile(
    controllerDir: string,
    outputFile: string,
): Promise<{ count: number; controllers: string[] }> {
    const controllers = await scanControllers(controllerDir)
    const content = generateRoutesContent(controllers)

    await Deno.writeTextFile(outputFile, content)

    return {
        count: controllers.length,
        controllers: controllers.map((c) => c.className),
    }
}
