/**
 * Controllers Registry
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by the routes system
 * 
 * In development mode (APP_ENV=development), controllers are auto-discovered.
 * In production/compile mode, this registry is used.
 */

import { ApiDocsController } from '@controller/api_docs_controller.ts'
import { AppController } from '@controller/app_controller.tsx'
import { AuthController } from '@controller/auth_controller.tsx'
import { DemoController } from '@controller/demo_controller.tsx'
import { DocsController } from '@controller/docs_controller.tsx'
import { LlmController } from '@controller/llm_controller.tsx'
import { UiController } from '@controller/ui_controller.tsx'

export const controllers = [
    ApiDocsController,
    AppController,
    AuthController,
    DemoController,
    DocsController,
    LlmController,
    UiController,
]
