#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run
/**
 * Dependency Analyzer for Lockness Monorepo
 *
 * Analyzes all @lockness/* packages and generates:
 * - Dependency graph in Markdown
 * - Cycle detection
 * - Architecture validation
 */

import { join } from '@std/path'
import { exists } from '@std/fs'

interface PackageInfo {
    name: string
    path: string
    version: string
    dependencies: string[]
}

interface DependencyGraph {
    packages: Map<string, PackageInfo>
    edges: Map<string, Set<string>>
}

/**
 * Parse a deno.json file and extract package info
 */
async function parsePackage(packageDir: string): Promise<PackageInfo | null> {
    const denoJsonPath = join(packageDir, 'deno.json')

    if (!await exists(denoJsonPath)) {
        return null
    }

    const content = await Deno.readTextFile(denoJsonPath)
    const config = JSON.parse(content)

    const name = config.name?.replace('@lockness/', '') || ''
    const version = config.version || '0.0.0'
    const imports = config.imports || {}

    // Extract @lockness/* dependencies (both direct and aliased)
    const dependencies: string[] = []
    for (const [key, value] of Object.entries(imports)) {
        if (typeof value !== 'string') continue

        // Case 1: Direct dependency "@lockness/xxx": "jsr:@lockness/xxx@..."
        if (key.startsWith('@lockness/')) {
            const depName = key.replace('@lockness/', '')
            dependencies.push(depName)
        } // Case 2: Aliased dependency "hono": "jsr:@lockness/hono@..."
        else if (
            value.includes('jsr:@lockness/') || value.includes('npm:@lockness/')
        ) {
            const match = value.match(/@lockness\/([^@]+)/)
            if (match) {
                dependencies.push(match[1])
            }
        }
    }

    return {
        name,
        path: packageDir,
        version,
        dependencies,
    }
}

/**
 * Scan all packages in the monorepo
 */
async function scanPackages(): Promise<DependencyGraph> {
    const packagesDir = 'packages'
    const packages = new Map<string, PackageInfo>()
    const edges = new Map<string, Set<string>>()

    for await (const entry of Deno.readDir(packagesDir)) {
        if (!entry.isDirectory || entry.name.startsWith('.')) {
            continue
        }

        const packagePath = join(packagesDir, entry.name)
        const packageInfo = await parsePackage(packagePath)

        if (packageInfo) {
            packages.set(packageInfo.name, packageInfo)
            edges.set(packageInfo.name, new Set(packageInfo.dependencies))
        }
    }

    return { packages, edges }
}

/**
 * Detect cycles in the dependency graph using DFS
 */
function detectCycles(graph: DependencyGraph): string[][] {
    const cycles: string[][] = []
    const visited = new Set<string>()
    const recursionStack = new Set<string>()
    const currentPath: string[] = []

    function dfs(node: string): void {
        visited.add(node)
        recursionStack.add(node)
        currentPath.push(node)

        const deps = graph.edges.get(node) || new Set()
        for (const dep of deps) {
            if (!graph.packages.has(dep)) {
                // External dependency, skip
                continue
            }

            if (!visited.has(dep)) {
                dfs(dep)
            } else if (recursionStack.has(dep)) {
                // Cycle detected
                const cycleStart = currentPath.indexOf(dep)
                const cycle = [...currentPath.slice(cycleStart), dep]
                cycles.push(cycle)
            }
        }

        currentPath.pop()
        recursionStack.delete(node)
    }

    for (const pkg of graph.packages.keys()) {
        if (!visited.has(pkg)) {
            dfs(pkg)
        }
    }

    return cycles
}

/**
 * Generate markdown documentation
 */
function generateMarkdown(graph: DependencyGraph, cycles: string[][]): string {
    const lines: string[] = [
        '# Lockness Monorepo - Dependency Architecture',
        '',
        '> 🤖 This document is auto-generated by `deno task deps:analyze`',
        '',
        '## Overview',
        '',
        `The Lockness monorepo contains **${graph.packages.size} packages** with the following dependency structure:`,
        '',
    ]

    // Cycle detection section
    if (cycles.length > 0) {
        lines.push('## ⚠️ Circular Dependencies Detected')
        lines.push('')
        lines.push('The following circular dependencies were found:')
        lines.push('')
        cycles.forEach((cycle, index) => {
            lines.push(
                `${index + 1}. ${
                    cycle.map((p) => `\`@lockness/${p}\``).join(' → ')
                }`,
            )
        })
        lines.push('')
    } else {
        lines.push('## ✅ No Circular Dependencies')
        lines.push('')
        lines.push('The dependency graph is acyclic (DAG).')
        lines.push('')
    }

    // Architecture layers
    lines.push('## Architecture Layers')
    lines.push('')
    lines.push('### Foundation Layer')
    lines.push(
        '- **`@lockness/contract`**: Core contracts, types, and decorators',
    )
    lines.push(
        '- **`@lockness/hono`**: Hono bridge (wrapper around `npm:hono`)',
    )
    lines.push('')
    lines.push('### Implementation Layer')
    lines.push('- **`@lockness/container`**: DI container implementation')
    lines.push('- Feature packages: `auth`, `session`, `cache`, `queue`, etc.')
    lines.push('')
    lines.push('### Orchestration Layer')
    lines.push(
        '- **`@lockness/core`**: Main framework orchestrator (re-exports everything)',
    )
    lines.push('')

    // Dependency tree for all packages
    lines.push('## Complete Dependency Tree')
    lines.push('')
    lines.push('```')

    // Sort packages by name
    const sortedPackages = Array.from(graph.packages.keys()).sort()

    sortedPackages.forEach((pkgName) => {
        const pkg = graph.packages.get(pkgName)!
        const deps = graph.edges.get(pkgName) || new Set()

        if (deps.size === 0) {
            // Package with no dependencies
            lines.push(`${pkgName} (v${pkg.version})`)
        } else {
            // Package with dependencies - show tree
            lines.push(`${pkgName} (v${pkg.version})`)
            const depsArray = Array.from(deps).filter((d) =>
                graph.packages.has(d)
            ).sort()
            depsArray.forEach((dep, index) => {
                const isLast = index === depsArray.length - 1
                const connector = isLast ? '└── ' : '├── '
                const depPkg = graph.packages.get(dep)
                lines.push(`${connector}${dep} (v${depPkg?.version || '?'})`)

                // Show transitive dependencies
                const transDeps = graph.edges.get(dep) || new Set()
                if (transDeps.size > 0) {
                    const prefix = isLast ? '    ' : '│   '
                    const transDepsArray = Array.from(transDeps).filter((d) =>
                        graph.packages.has(d)
                    ).sort()
                    transDepsArray.forEach((transDep, transIndex) => {
                        const transIsLast =
                            transIndex === transDepsArray.length - 1
                        const transConnector = transIsLast ? '└── ' : '├── '
                        const transPkg = graph.packages.get(transDep)
                        lines.push(
                            `${prefix}${transConnector}${transDep} (v${
                                transPkg?.version || '?'
                            })`,
                        )
                    })
                }
            })
        }
        lines.push('')
    })

    lines.push('```')
    lines.push('')

    // Package details
    lines.push('## Package Details')
    lines.push('')

    const sortedPackagesList = Array.from(graph.packages.values())
        .sort((a, b) => a.name.localeCompare(b.name))

    for (const pkg of sortedPackagesList) {
        lines.push(`### @lockness/${pkg.name}`)
        lines.push('')
        lines.push(`**Version**: ${pkg.version}`)
        lines.push('')

        if (pkg.dependencies.length === 0) {
            lines.push('**Dependencies**: None')
        } else {
            lines.push('**Dependencies**:')
            lines.push('')
            lines.push('```')

            // Show dependency tree
            pkg.dependencies.forEach((dep, index) => {
                const isLast = index === pkg.dependencies.length - 1
                const connector = isLast ? '└── ' : '├── '
                const depPkg = graph.packages.get(dep)
                lines.push(
                    `${connector}@lockness/${dep} (v${depPkg?.version || '?'})`,
                )

                // Show transitive dependencies
                const transDeps = graph.edges.get(dep) || new Set()
                if (transDeps.size > 0) {
                    const prefix = isLast ? '    ' : '│   '
                    const transDepsArray = Array.from(transDeps).filter((d) =>
                        graph.packages.has(d)
                    ).sort()
                    transDepsArray.forEach((transDep, transIndex) => {
                        const transIsLast =
                            transIndex === transDepsArray.length - 1
                        const transConnector = transIsLast ? '└── ' : '├── '
                        const transPkg = graph.packages.get(transDep)
                        lines.push(
                            `${prefix}${transConnector}@lockness/${transDep} (v${
                                transPkg?.version || '?'
                            })`,
                        )
                    })
                }
            })

            lines.push('```')
        }

        lines.push('')
    }

    // Architecture rules
    lines.push('## Architecture Rules')
    lines.push('')
    lines.push(
        '1. **No package should depend on** `@lockness/core` **(except for end-user applications)**',
    )
    lines.push(
        '2. `@lockness/contract` **has zero internal dependencies** (only external: `@lockness/hono`, `@std/*`)',
    )
    lines.push(
        '3. **Feature packages depend on** `@lockness/contract` **for types and decorators**',
    )
    lines.push(
        '4. `@lockness/core` **is the orchestrator that assembles and re-exports everything**',
    )
    lines.push('')

    return lines.join('\n')
}

/**
 * Main execution
 */
async function main() {
    console.log('🔍 Scanning packages...')
    const graph = await scanPackages()

    console.log(`📦 Found ${graph.packages.size} packages`)

    console.log('🔄 Detecting cycles...')
    const cycles = detectCycles(graph)

    if (cycles.length > 0) {
        console.log(`⚠️  Found ${cycles.length} circular dependencies!`)
        cycles.forEach((cycle, index) => {
            console.log(`   ${index + 1}. ${cycle.join(' → ')}`)
        })
    } else {
        console.log('✅ No circular dependencies detected')
    }

    console.log('📝 Generating documentation...')
    const markdown = generateMarkdown(graph, cycles)

    const outputPath = 'docs/dependencies.md'
    await Deno.mkdir('docs', { recursive: true })
    await Deno.writeTextFile(outputPath, markdown)

    console.log(`✅ Documentation generated: ${outputPath}`)

    // Format the generated file
    try {
        const command = new Deno.Command(Deno.execPath(), {
            args: ['fmt', outputPath],
        })
        const { success } = await command.output()
        if (success) {
            console.log(`✨ Documentation formatted: ${outputPath}`)
        }
    } catch (error) {
        console.warn(`⚠️  Failed to format documentation: ${error}`)
    }

    // Exit with error code if cycles detected
    if (cycles.length > 0) {
        Deno.exit(1)
    }
}

if (import.meta.main) {
    main()
}
