/**
 * @fileoverview AUTO-GENERATED UI EXAMPLES REGISTRY
 * 
 * This file is automatically generated.
 * It enables static linking of UI examples for production builds (deno compile).
 */

import * as SteppedProgressExamples from './components/SteppedProgress/examples.tsx';
import * as SearchBarExamples from './components/SearchBar/examples.tsx';
import * as TabsExamples from './components/Tabs/examples.tsx';
import * as SidebarExamples from './components/Sidebar/examples.tsx';
import * as KbdExamples from './components/Kbd/examples.tsx';
import * as ThemeSwitchExamples from './components/ThemeSwitch/examples.tsx';
import * as NavbarExamples from './components/Navbar/examples.tsx';
import * as PaginationExamples from './components/Pagination/examples.tsx';
import * as VideoExamples from './components/Video/examples.tsx';
import * as GaugeProgressExamples from './components/GaugeProgress/examples.tsx';
import * as CardExamples from './components/Card/examples.tsx';
import * as ProgressExamples from './components/Progress/examples.tsx';
import * as CodeBlockExamples from './components/CodeBlock/examples.tsx';
import * as TreeViewExamples from './components/TreeView/examples.tsx';
import * as InputExamples from './components/Input/examples.tsx';
import * as AlertExamples from './components/Alert/examples.tsx';
import * as AccordionExamples from './components/Accordion/examples.tsx';
import * as SkeletonExamples from './components/Skeleton/examples.tsx';
import * as SeparatorExamples from './components/Separator/examples.tsx';
import * as GalleryExamples from './components/Gallery/examples.tsx';
import * as ChartExamples from './components/Chart/examples.tsx';
import * as CheckboxExamples from './components/Checkbox/examples.tsx';
import * as SpinnerExamples from './components/Spinner/examples.tsx';
import * as UploadZoneExamples from './components/UploadZone/examples.tsx';
import * as ButtonExamples from './components/Button/examples.tsx';
import * as TableExamples from './components/Table/examples.tsx';
import * as SwitchExamples from './components/Switch/examples.tsx';
import * as BreadcrumbExamples from './components/Breadcrumb/examples.tsx';
import * as NewsletterExamples from './components/Newsletter/examples.tsx';
import * as HeroExamples from './components/Hero/examples.tsx';
import * as ModalExamples from './components/Modal/examples.tsx';
import * as PricingExamples from './components/Pricing/examples.tsx';
import * as BadgeExamples from './components/Badge/examples.tsx';
import * as CircularProgressExamples from './components/CircularProgress/examples.tsx';

export const uiExamplesRegistry: Record<string, any> = {
    'stepped-progress': SteppedProgressExamples.examples,
    'search-bar': SearchBarExamples.examples,
    'tabs': TabsExamples.examples,
    'sidebar': SidebarExamples.examples,
    'keyboards': KbdExamples.examples,
    'theme-switch': ThemeSwitchExamples.examples,
    'navbar': NavbarExamples.examples,
    'pagination': PaginationExamples.examples,
    'video': VideoExamples.examples,
    'gauge-progress': GaugeProgressExamples.examples,
    'cards': CardExamples.examples,
    'progress': ProgressExamples.examples,
    'code-block': CodeBlockExamples.examples,
    'treeview': TreeViewExamples.examples,
    'inputs': InputExamples.examples,
    'forms': InputExamples.examples,
    'alerts': AlertExamples.examples,
    'accordion': AccordionExamples.examples,
    'skeleton': SkeletonExamples.examples,
    'skeletons': SkeletonExamples.examples,
    'separator': SeparatorExamples.examples,
    'separators': SeparatorExamples.examples,
    'gallery': GalleryExamples.examples,
    'chart': ChartExamples.examples,
    'checkboxes': CheckboxExamples.examples,
    'spinner': SpinnerExamples.examples,
    'upload-zone': UploadZoneExamples.examples,
    'buttons': ButtonExamples.examples,
    'table': TableExamples.examples,
    'switches': SwitchExamples.examples,
    'breadcrumb': BreadcrumbExamples.examples,
    'navigation': BreadcrumbExamples.examples,
    'newsletter': NewsletterExamples.examples,
    'hero': HeroExamples.examples,
    'modal': ModalExamples.examples,
    'pricing': PricingExamples.examples,
    'badges': BadgeExamples.examples,
    'circular-progress': CircularProgressExamples.examples,
};
