/**
 * @fileoverview Generator for UI examples registry.
 *
 * Scans all component directories for examples.tsx and generates
 * a static registry file for production builds (deno compile).
 *
 * @module @lockness/ui/registry_generator
 */

import { walk } from '@std/fs'
import { basename, dirname, fromFileUrl, join } from '@std/path'

/**
 * Generates the static UI examples registry file.
 *
 * @param componentsDir - Path to the components directory
 * @param outputFile - Path where to write the registry file
 */
export async function generateUiRegistry(
    componentsDir: string,
    outputFile: string,
) {
    console.log('🎨 Generating UI examples registry...')

    const examples: { slug: string; importPath: string; className: string }[] =
        []

    // Slug to Component mapping
    const slugMap: Record<string, string> = {
        'buttons': 'Button',
        'cards': 'Card',
        'feature-cards': 'FeatureCard',
        'inputs': 'Input',
        'textareas': 'Textarea',
        'labels': 'Label',
        'checkboxes': 'Checkbox',
        'switches': 'Switch',
        'badges': 'Badge',
        'alerts': 'Alert',
        'accordion': 'Accordion',
        'modal': 'Modal',
        'table': 'Table',
        'tabs': 'Tabs',
        'progress': 'Progress',
        'circular-progress': 'CircularProgress',
        'stepped-progress': 'SteppedProgress',
        'gauge-progress': 'GaugeProgress',
        'breadcrumb': 'Breadcrumb',
        'links': 'Link',
        'spinner': 'Spinner',
        'skeleton': 'Skeleton',
        'skeletons': 'Skeleton',
        'separator': 'Separator',
        'separators': 'Separator',
        'gallery': 'Gallery',
        'video': 'Video',
        'hero': 'Hero',
        'navbar': 'Navbar',
        'newsletter': 'Newsletter',
        'pagination': 'Pagination',
        'pricing': 'Pricing',
        'search-bar': 'SearchBar',
        'sidebar': 'Sidebar',
        'theme-switch': 'ThemeSwitch',
        'treeview': 'TreeView',
        'upload-zone': 'UploadZone',
        'keyboards': 'Kbd',
        'chart': 'Chart',
        'code-block': 'CodeBlock',
        'copy-button': 'CopyButton',
        'footer': 'Footer',
        'root-layout': 'RootLayout',
        'section': 'Section',
        'title': 'Title',
        'props-table': 'PropsTable',
        'chart-extras': 'ChartExtras',
        'forms': 'Input',
        'navigation': 'Breadcrumb',
    }

    // Inverse map for lookup
    const componentToSlugs: Record<string, string[]> = {}
    for (const [slug, component] of Object.entries(slugMap)) {
        if (!componentToSlugs[component]) componentToSlugs[component] = []
        componentToSlugs[component].push(slug)
    }

    // Scan for examples.tsx
    for await (
        const entry of walk(componentsDir, {
            maxDepth: 2,
            includeDirs: false,
            match: [/examples\.tsx$/],
        })
    ) {
        const componentName = basename(join(entry.path, '..'))
        const slugs = componentToSlugs[componentName] ||
            [componentName.toLowerCase()]

        const relativeImportPath = `./components/${componentName}/examples.tsx`
        const className = `${componentName}Examples`

        for (const slug of slugs) {
            examples.push({ slug, importPath: relativeImportPath, className })
        }
    }

    // Generate file content
    const uniqueImports = Array.from(new Set(examples.map((e) => e.importPath)))
    const importStats = uniqueImports.map((path) => {
        const componentName = basename(join(path, '..'))
        return `import * as ${componentName}Examples from '${path}';`
    }).join('\n')

    const registryEntries = examples.map((e) => {
        return `    '${e.slug}': ${e.className}.examples,`
    }).join('\n')

    const content = `/**
 * @fileoverview AUTO-GENERATED UI EXAMPLES REGISTRY
 * 
 * This file is automatically generated.
 * It enables static linking of UI examples for production builds (deno compile).
 */

${importStats}

export const uiExamplesRegistry: Record<string, any> = {
${registryEntries}
};
`

    await Deno.writeTextFile(outputFile, content)

    // Format the file to match project style
    try {
        const command = new Deno.Command(Deno.execPath(), {
            args: ['fmt', outputFile],
        })
        await command.output()
    } catch (_e) {
        // Ignore failures to format
    }

    console.log(
        `✅ Generated UI examples registry with ${examples.length} entries.`,
    )
}

/**
 * CLI entry point for the registry generator.
 */
if (import.meta.main) {
    const pkgDir = dirname(fromFileUrl(import.meta.url))
    const componentsDir = join(pkgDir, 'components')
    const outputFile = join(pkgDir, 'examples_registry.ts')
    await generateUiRegistry(componentsDir, outputFile)
}
