/**
 * @fileoverview `make:action` adds its imports to a controller generated by
 * `make:controller` (#436 review).
 *
 * The fixture is rendered from the real `controller.stub`, so a stub that
 * changes its import specifier breaks these tests rather than leaving
 * `make:action` editing an import that no longer exists.
 *
 * @module @lockness/cli/tests/make_action
 */

import { assert, assertEquals } from '@std/assert'
import { Cli } from '../mod.ts'
import { MAKE_COMMANDS } from '../commands/make/index.ts'
import { STUBS_PATH } from '../commands/make/stub_paths.ts'
import { Stub } from '../stubs.ts'
import { captureConsole, inTempDir } from './helpers.ts'

/** A `Cli` with every `make:*` command registered. */
function makeCli(): Cli {
    const cli = new Cli()
    for (const command of MAKE_COMMANDS) {
        cli.register(command.name, command.handler, command.description)
    }
    return cli
}

/** Write `app/controller/<name>_controller.tsx` from the real stub. */
async function writeStubController(className: string): Promise<string> {
    const route = className.toLowerCase()
    const path = `app/controller/${route}_controller.tsx`
    const content = await Stub.renderFrom(STUBS_PATH, 'make', 'controller', {
        className,
        route,
    })
    await Deno.mkdir('app/controller', { recursive: true })
    await Deno.writeTextFile(path, content)
    return path
}

/** Run `make:action` in a temp dir holding `prepare`'s controller. */
function runAction(
    args: string[],
    prepare: () => Promise<string>,
): Promise<{ status: number; controller: string; error: unknown[][] }> {
    return inTempDir(async () => {
        const path = await prepare()
        const { result, error } = await captureConsole(() =>
            makeCli().dispatch(['make:action', ...args])
        )
        return {
            status: result,
            controller: await Deno.readTextFile(path),
            error,
        }
    })
}

/** The source lines of `content` that import from `@lockness/core`. */
function coreImportLines(content: string): string[] {
    return content.split('\n').filter((line) =>
        /from\s*['"]@lockness\/core['"]/.test(line)
    )
}

/** The names imported by the one `@lockness/core` import of `content`. */
function coreImportNames(content: string): string[] {
    const lines = coreImportLines(content)
    assertEquals(lines.length, 1, content)
    const match = lines[0].match(/import\s*{([^}]+)}/)
    assert(match, lines[0])
    return match[1].split(',').map((name) => name.trim())
}

Deno.test('make:action - decorator import', async (t) => {
    await t.step('--method=post adds Post to the stub import', async () => {
        const { status, controller, error } = await runAction(
            ['User', 'store', '--method=post'],
            () => writeStubController('User'),
        )

        assertEquals(status, 0, String(error))
        assert(coreImportNames(controller).includes('Post'), controller)
        assert(!controller.includes("'lockness/core'"), controller)
    })

    await t.step(
        'a class named like the decorator does not hide it',
        async () => {
            // `PostController` contains `Post`; the import still lacks it.
            const { status, controller, error } = await runAction(
                ['Post', 'store', '--method=post'],
                () => writeStubController('Post'),
            )

            assertEquals(status, 0, String(error))
            assert(coreImportNames(controller).includes('Post'), controller)
        },
    )

    await t.step('a decorator already imported is not repeated', async () => {
        const { controller } = await runAction(
            ['User', 'about'],
            () => writeStubController('User'),
        )

        const names = coreImportNames(controller)
        assertEquals(names.filter((name) => name === 'Get').length, 1)
    })

    await t.step(
        'a controller without the import gets one at the top',
        async () => {
            const { status, controller, error } = await runAction(
                ['User', 'store', '--method=post'],
                async () => {
                    await Deno.mkdir('app/controller', { recursive: true })
                    const path = 'app/controller/user_controller.tsx'
                    await Deno.writeTextFile(
                        path,
                        'export class UserController {\n}\n',
                    )
                    return path
                },
            )

            assertEquals(status, 0, String(error))
            assert(
                controller.startsWith(
                    "import { Post } from '@lockness/core'\n",
                ),
                controller,
            )
        },
    )
})

Deno.test('make:action - view import', async (t) => {
    await t.step(
        '--view imports the view right after @lockness/core',
        async () => {
            const { status, controller, error } = await runAction(
                ['User', 'show', '--view'],
                () => writeStubController('User'),
            )

            assertEquals(status, 0, String(error))
            const lines = controller.split('\n')
            const core = lines.findIndex((line) =>
                line.includes("from '@lockness/core'")
            )
            assert(core >= 0, controller)
            assertEquals(
                lines[core + 1],
                "import { UserShow } from '@view/pages/user/show.tsx'",
            )
            assert(controller.includes('<UserShow />'), controller)
        },
    )
})
